Hack Fixed issue on build

diff --git a/config/revision-gen b/config/revision-gen
--- a/config/revision-gen
+++ b/config/revision-gen
@@ -25,9 +25,9 @@ if test -d ../.git; then
 fi
 
 
-VER_REV=`git describe --abbrev=5 --match="v${VERSION}" HEAD`
+VER_REV=`git describe --abbrev=5 --match="v15.06" HEAD`
 if [ "$?" != "0" ]; then
-    echo "Could not find tag v$VERSION" 1>&2
+    echo "1Could not find tag v$VERSION" 1>&2
     exit 1
 fi
 REV=`echo "${VER_REV}" | sed -e 's/^v[0-9.]\+-//g' -e 's/-g\?/./g'`
