Pull bugfixes from sipxcom release-18.08

diff --git a/sipXconfig/bin/mongo-local-arbiter.in b/sipXconfig/bin/mongo-local-arbiter.in
--- a/sipXconfig/bin/mongo-local-arbiter.in
+++ b/sipXconfig/bin/mongo-local-arbiter.in
@@ -1,77 +1,112 @@
 #!/bin/bash
 
-# mongo-local-arbiter - Startup script for mongod local arbiter
+# mongod - Startup script for mongod arbiter
 
 # chkconfig: 35 85 15
-# description: Mongodb arbiter unblocks tie votes in local dbs on new primary should it become unavailable
-# processname: mongod
+# description: Mongo is a scalable, document-oriented database.
+# processname: mongo-local-arbiter
 # config: /etc/mongo-local-arbiter.conf
-# pidfile: /var/run/mongo/local-arbiter.pid
-
-# NOTE: This file cloned from /etc/init.d/mongod from mongodb proper
 
 . /etc/rc.d/init.d/functions
 
-# things from mongod.conf get there by mongod reading it
-
 # NOTE: if you change any OPTIONS here, you get what you pay for:
-# this script assumes all options are in the config file.
-CONFIGFILE="/etc/mongo-local-arbiter.conf"
-OPTIONS=" -f $CONFIGFILE"
-SYSCONFIG="/etc/sysconfig/mongo-local-arbiter"
-LOCKFILE=/var/lock/subsys/mongo-local-arbiter
-
-# 10gen v.s. fedora
-if `id mongodb 1>/dev/null 2>&1` ; then
-  # fedora
-  MONGO_USER=mongodb
-  MONGO_GROUP=mongodb
-else
-  # 10gen
-  MONGO_USER=mongod
-  MONGO_GROUP=mongod
+# this script assumes all options are in the config file.                                                                                                                                                                                    
+CONFIGFILE="/etc/mongo-local-arbiter.conf"                                                                                                                                                                                                        
+OPTIONS=" -f $CONFIGFILE"                                                                                                                                                                                                                    
+                                                                                                                                                                                                                                             
+mongod=${MONGOD-/usr/bin/mongod}                                                                                                                                                                                                             
+                                                                                                                                                                                                                                             
+MONGO_USER=mongod                                                                                                                                                                                                                            
+MONGO_GROUP=mongod                                                                                                                                                                                                                           
+                                                                                                                                                                                                                                             
+# All variables set before this point can be overridden by users, by                                                                                                                                                                         
+# setting them directly in the SYSCONFIG file. Use this to explicitly                                                                                                                                                                        
+# override these values, at your own risk.                                                                                                                                                                                                   
+SYSCONFIG="/etc/sysconfig/mongo-local-arbiter"                                                                                                                                                                                                    
+if [ -f "$SYSCONFIG" ]; then                                                                                                                                                                                                                 
+    . "$SYSCONFIG"                                                                                                                                                                                                                           
+fi                                                                                                                                                                                                                                           
+                                                                                                                                                                                                                                             
+# Handle NUMA access to CPUs (SERVER-3574)                                                                                                                                                                                                   
+# This verifies the existence of numactl as well as testing that the command works                                                                                                                                                           
+NUMACTL_ARGS="--interleave=all"                                                                                                                                                                                                              
+if which numactl >/dev/null 2>/dev/null && numactl $NUMACTL_ARGS ls / >/dev/null 2>/dev/null                                                                                                                                                 
+then                                                                                                                                                                                                                                         
+    NUMACTL="numactl $NUMACTL_ARGS"                                                                                                                                                                                                          
+else                                                                                                                                                                                                                                         
+    NUMACTL=""
 fi
 
-test -f $CONFIGFILE || exit 5
-
-# FIXME: 1.9.x has a --shutdown flag that parses the config file and
-# shuts down the correct running pid, but that's unavailable in 1.8
-# for now.  This can go away when this script stops supporting 1.8.
-DBPATH=`awk -F= '/^dbpath ?= ?/{print $2}' "$CONFIGFILE"`
-PIDFILE=`awk -F= '/^pidfilepath ?= ?/{print $2}' "$CONFIGFILE"`
-mongod=${MONGOD-/usr/bin/mongod}
-
-! test -d $DBPATH || mkdir -p $DBPATH
-chown $MONGO_USER:$MONGO_GROUP $DBPATH
-
-! test -f "$SYSCONFIG" || . "$SYSCONFIG"
-
+# things from mongod.conf get there by mongod reading it
+PIDFILEPATH="`awk -F'[:=]' -v IGNORECASE=1 '/^[[:blank:]]*(processManagement\.)?pidfilepath[[:blank:]]*[:=][[:blank:]]*/{print $2}' \"$CONFIGFILE\" | tr -d \"[:blank:]\\"'\" | awk -F'#' '{print $1}'`"
+PIDDIR=`dirname $PIDFILEPATH`
 start()
 {
-  echo -n $"Starting mongo-local-arbiter: "
-  daemon --user "$MONGO_USER" $mongod $OPTIONS
+  # Make sure the default pidfile directory exists
+  if [ ! -d $PIDDIR ]; then
+    install -d -m 0755 -o $MONGO_USER -g $MONGO_GROUP $PIDDIR
+  fi
+  # Make sure the pidfile does not exist
+  if [ -f "$PIDFILEPATH" ]; then
+      echo "Error starting mongod. $PIDFILEPATH exists."
+      RETVAL=1
+      return
+  fi
+  # Recommended ulimit values for mongod or mongos
+  # See http://docs.mongodb.org/manual/reference/ulimit/#recommended-settings
+  #
+  ulimit -f unlimited
+  ulimit -t unlimited
+  ulimit -v unlimited
+  ulimit -n 64000
+  ulimit -m unlimited
+  ulimit -u 64000
+  echo -n $"Starting mongod: "
+  daemon --user "$MONGO_USER" --check $mongod "$NUMACTL $mongod $OPTIONS >/dev/null 2>&1"
   RETVAL=$?
   echo
-  [ $RETVAL -eq 0 ] && touch $LOCKFILE
+  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/mongo-local-arbiter
 }
-
 stop()
 {
-  echo -n $"Stopping mongo-local-arbiter: "
-  killproc -p $PIDFILE $mongod
+  echo -n $"Stopping mongod: "
+  mongo_killproc "$PIDFILEPATH" $mongod
   RETVAL=$?
   echo
-  [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
+  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/mongo-local-arbiter
 }
-
 restart () {
-	stop
-	start
+        stop
+        start
 }
-
-ulimit -n 12000
+# Send TERM signal to process and wait up to 300 seconds for process to go away.
+# If process is still alive after 300 seconds, send KILL signal.
+# Built-in killproc() (found in /etc/init.d/functions) is on certain versions of Linux
+# where it sleeps for the full $delay seconds if process does not respond fast enough to
+# the initial TERM signal.
+mongo_killproc()
+{
+  local pid_file=$1
+  local procname=$2
+  local -i delay=300
+  local -i duration=10
+  local pid=`pidofproc -p "${pid_file}" ${procname}`
+  kill -TERM $pid >/dev/null 2>&1
+  usleep 100000
+  local -i x=0
+  while [ $x -le $delay ] && checkpid $pid; do
+    sleep $duration
+    x=$(( $x + $duration))
+  done
+  kill -KILL $pid >/dev/null 2>&1
+  usleep 100000
+  checkpid $pid # returns 0 only if the process exists
+  local RC=$?
+  [ "$RC" -eq 0 ] && failure "${procname} shutdown" || rm -f "${pid_file}"; success "${procname} shutdown"
+  RC=$((! $RC)) # invert return code so we return 0 when process is dead.
+  return $RC
+}
 RETVAL=0
-
 case "$1" in
   start)
     start
@@ -83,15 +118,14 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f $LOCKFILE ] && restart || :
+    [ -f /var/lock/subsys/mongo-local-arbiter ] && restart || :
     ;;
   status)
-    status -p $PIDFILE "mongo-local-arbiter"
+    status $mongod
     RETVAL=$?
     ;;
   *)
     echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
     RETVAL=1
 esac
-
 exit $RETVAL
